"""crea tabla de cambio de estado

Revision ID: ae7c1fa8e57e
Revises: 
Create Date: 2023-11-04 16:43:56.873066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7c1fa8e57e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cambios_estado_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.alter_column('contenido',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('creador',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('creador',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.alter_column('contenido',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    op.drop_table('cambios_estado_ticket')
    # ### end Alembic commands ###
